name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: 1.23
    - uses: actions/checkout@v4
    - run: make clean tools lint goimports vet
    - run: go build
    - run: ./sqsmv -version
